# .github/workflows/deploy-frontend.yml
name: Deploy Frontend Terraform

on:
  push:
    branches:
      - main
      - prod
    paths:
      - front/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker southamerica-west1-docker.pkg.dev

      - name: Build Docker Image
        if : github.ref == 'refs/heads/main'
        run: |
          docker build -t southamerica-west1-docker.pkg.dev/uade-476411/frontend/dev:latest -f front/Dockerfile front

      - name: Build Docker Image
        if : github.ref == 'refs/heads/prod'
        run: |
          docker build -t southamerica-west1-docker.pkg.dev/uade-476411/frontend/prod:latest -f front/Dockerfile front

      - name: Push Docker Image
        if : github.ref == 'refs/heads/main'
        run: |
          docker push southamerica-west1-docker.pkg.dev/uade-476411/frontend/dev:latest
          
      - name: Push Docker Image
        if : github.ref == 'refs/heads/prod'
        run: |
          docker push southamerica-west1-docker.pkg.dev/uade-476411/frontend/prod:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Deploy with Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve -target=google_artifact_registry_repository.frontend
          terraform apply -auto-approve -target=google_cloud_run_service.frontend_dev
      
      - name: Deploy with Terraform 
        if: github.ref == 'refs/heads/prod'
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve -target=google_artifact_registry_repository.frontend
          terraform apply -auto-approve -target=google_cloud_run_service.frontend_prod
