# .github/workflows/deploy-frontend.yml
name: Deploy Frontend Terraform

on:
  push:
    branches:
      - main
      - prod
    paths:
      - front/**
      - infra/**/frontend.tf
      - .github/workflows/deploy-frontend.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Initialize Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra/dev
          terraform init

      - name: Initialize Terraform
        if: github.ref == 'refs/heads/prod'
        run: |
          cd infra/prod
          terraform init

      - name: Terraform Repository Setup
        run: terraform apply -auto-approve -target=google_artifact_registry_repository.frontend

      - name: Deploy
        run: terraform apply -auto-approve -target=google_cloud_run_service.frontend
