# .github/workflows/deploy-backend.yml
name: Deploy Backend Terraform

on:
  push:
    branches:
      - main
      - prod
    paths:
      - back/**
      - infra/**/backend.tf
      - .github/workflows/deploy-backend.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker southamerica-west1-docker.pkg.dev

      - name: Start Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Initialize and Run Terraform (Dev)
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra/dev
          terraform init
          terraform apply -auto-approve -target="google_cloud_run_service.backend"


      - name: Initialize and Run Terraform (Prod)
        if: github.ref == 'refs/heads/prod'
        run: |
          cd infra/prod
          terraform init
          terraform apply -auto-approve -target="google_cloud_run_service.backend"
